### ISSUE TITLE
Significant Sargan test

### ISSUE THREAD

**Issue by sayrhe** [zackfisher/MIIVsem#2]
Hi,

It is my understanding that a statistically significant Sargan test with >1 dfs means that some of the MIIVs are correlated with the composite error of that equation. If that happens what options one has to examine which ones of the MIIVs are problematic? Should I use the "instruments" argument of miive command to e.g. drop one MIIV at the time from the set of MIIVs to explore what MIIV is correlated with the error? And if I use the "instruments" argument, should I also define MIIVs for the other equations by hand as well?

Cheers,
Samuli

**Comment by zackfisher** [comment]
Hi Samuli,

In following up a significant overidentification test one possibility is to determine which model misspecifications might have led to the inclusion of invalid instruments. This is not always straightforward in complex models, however, it is certainly possible to narrow down the suspects using some of the published robustness conditions.  For example, if the equation in question comes from the measurement model the misspecification is likely also within the measurement model. A MIIV might be incorrectly included in the MIIV set due to an omitted error covariance or cross-loading.  You can find more details on these robustness conditions here, 

https://www.tandfonline.com/doi/full/10.1080/10705511.2018.1456341. 

Second, it is also possible to conduct a chi-square difference test between two sets of MIIVs if you have more than one suspected bad instrument.  I hope this helps.

Zack
